media:
  input: public
  output: /
content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/blog
    view:
      fields: [ title, date ]
    fields:
      - { name: author, label: Author, type: string }
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string }
      - { name: body, label: Body, type: rich-text }
      - { name: pubDate, label: Date, type: date }
      - { name: updatedDate, label: Date, type: date }
      - { name: tags, label: Tags, type: string, list: true }
      # - { name: ogImage, label: Title, type: string }
      # - { name: featured, label: Featured, type: boolean }
      # - { name: draft, label: Draft, type: boolean }
      # - { name: slug, label: Slug, type: string }
  - name: about
    label: About page
    type: file
    path: src/pages/about.md
    fields:
      - { name: layout, type: string, hidden: true, default: "../layouts/AboutLayout.astro" }
      - { name: title, label: Title, type: string }
      - { name: body, label: Body, type: rich-text, options: { input: public/assets, output: /assets } }
